### ISSUE TITLE
Password Field Issue

### ISSUE THREAD

**Issue by kc2npu** [GustavBrock/VBA.Cryptography#2]
I would like to recommend an update to your tools in the BPassword module. 
In the AppendPasswordField function, you allow for the customization of the password field name. However, all of the other functions (PasswordExists, ReadPassword, ResetPassword, SavePassword and VerifyPassword) do not accept a value indicating the field's name and all assume that it is "Password"

**Comment by GustavBrock** [comment]
Good point. 

The reason is, as I remember it, that the functions were meant as a set of simple (tight) example functions for testing or _proof of operation_. 
Thus, for production use, you would or could easily modify or expand these as needed. For example, some dislike the reserved word _Password_ for a field name and, if so, you can easily change the constants as you probably not in the same application will have different field names for holding passwords. Of course, if you will have different names for password fields, you would have to include the field name as a parameter to all the functions.

Thank you for the feedback.

**Comment by GustavBrock** [comment]
Added option for custom table name and/or field name covering all functions.
